Bowling: Add new test
exercism/problem-specifications pull request #1633
Opened 2020-01-21 14:40 UTC by isgj

Following exercism/rust#916 I'm adding this test.

2020-01-21 14:57 UTC, cmccandless commented on exercises/bowling/canonical-data.json
> +  }, {
```suggestion
  },
  {
```

2020-01-21 16:59 UTC, rpottsoh commented
Yes this repo is still not accepting changes along the lines proposed by this PR.

However, there are two changes I would like to see made to this PR.

1.  Line 3: Version needs to be incremented per rules in [README](https://github.com/exercism/problem-specifications#test-data-versioning).
1.  I would like to see the new case moved up so that it is grouped with the other `Score` cases similar to this one.

Someday the freeze will be lifted and another good change will be ready to go.  👍

2022-01-12 13:45 UTC, ErikSchierboom commented
@isgj Are you still interested in working on this PR?

2022-01-26 12:08 UTC, ErikSchierboom commented
CC @exercism/reviewers maybe someone can review?

2022-01-27 07:49 UTC, kotp approved these changes
It looks right to me, and @petertseng reviewed it as it applies to Rust as well.

2022-01-27 08:59 UTC, ErikSchierboom approved these changes
My only comment would be to perhaps move this test case up a bit, as we usually try to order the test cases by order of increasing difficulty.

2022-01-27 09:00 UTC, ErikSchierboom requested changes
It looks like the JSON is invalid: https://github.com/exercism/problem-specifications/runs/4963687045?check_suite_focus=true

2022-01-27 09:23 UTC, ErikSchierboom commented
@isgj Thanks for the quick fix! There are two minor issues remaining:

1. It think it would make sense to move this new test case to https://github.com/exercism/problem-specifications/blob/ecf797f3086f9b70dec11d211e419ba02fcb8ad5/exercises/bowling/canonical-data.json#L107, along with the other valid bonus roll test cases. Would you be okay moving the test case?
2. The CI is failing because since this PR was opened, we introduced a `uuid` property to all test cases. Maybe you could rebase this PR on the latest `main` and add the `uuid` property to the new test case? You can generate one using https://www.uuidgenerator.net/version4. Sorry about that.

2022-01-27 11:43 UTC, ErikSchierboom approved these changes
Excellent. LGTM!

2022-01-27 19:23 UTC, kotp approved these changes

2022-01-27 22:15 UTC, petertseng approved these changes

2022-01-27 23:03 UTC, merged

2022-01-27 23:03 UTC, kotp commented
@isgj Thank you very much for the work done with this!