Update canonical-data.json
exercism/problem-specifications pull request #1652
Opened 2020-04-28 19:05 UTC by miguelraz

addresses #1651 

- brought to y'all by the Julia Gang

2020-04-28 19:14 UTC, SaschaMann commented
This test case is already given as example in the description, but not covered by tests. I'd argue it's a bug fix and not covered by #1560.

2020-04-28 19:25 UTC, SaschaMann approved these changes

2020-04-28 19:47 UTC, rpottsoh requested changes

2020-04-28 19:47 UTC, rpottsoh commented on exercises/resistor-color-trio/canonical-data.json
> +     {
```suggestion
    {
```
Remove single extra leading space.

2020-04-28 20:39 UTC, yawpitch commented
I'd  argue that it is _not_ a bug and that this PR is blocked by #1560. As stated by @iHiD in the body of that Issue a test would have to be _wrong_, not merely missing, to be considered a bug:

> We will still accept bugfixes (**if tests are wrong**) and improvements to the copy around exercises, as long as they do not alter the substance of an exercise

Emphasis added.

Though it would take some effort to survey them all, I believe there are a number of description.md files mention examples that do not literally exist in the tests. Certainly there are many descriptions that make assumptions / implications not actually addressed in tests. If this addition isn't actually testing anything _new_ and otherwise uncovered in the tests -- which it isn't _obviously_ doing, as all three colors appear in the same orientation in other tests -- then I'd argue it's not actually necessary, on top of not really being a bug fix.

2020-04-28 22:54 UTC, rpottsoh approved these changes

2020-04-28 23:07 UTC, rpottsoh commented
@miguelraz thanks for the making the change I requested.  I have to agree with @yawpitch though.  I recommend following the suggestion outlined in #1560 that suggests that changes be added at the local (track) level.  This test case could be added to the track where you came across this issue in the canonical data.  @exercism/julia was it?

Personally I think the suggested change is a good one for the canonical data.   I am going to close this PR for now.  

This PR should be reconsidered whenever the restrictions of #1560 are reversed.

2020-04-28 23:09 UTC, miguelraz commented
Thanks, I think @SaschaMann can help with the Julia local changes.

2020-04-29 13:12 UTC, iHiD commented
I've reopening with the `hold` tag for us to consider after #1560 is reversed.

2020-04-29 14:26 UTC, SaschaMann requested changes
(just to block the merge button while it's on hold)

2020-04-29 14:29 UTC, iHiD commented
@SaschaMann Nice idea. I believe y'all can also now convert PRs to drafts (I've just done that here)

2020-11-22 00:14 UTC, miguelraz commented
I believe #1560 is now reversed and this can be merged @SaschaMann .

2020-11-22 08:29 UTC, SaschaMann commented
It needs to be rebased, I think. The version can be dropped and the test case itself needs a UUID now.

2022-03-14 16:29 UTC, angelikatyborska requested changes
I'm not sure if `3300 ohms` is the correct return value for this case. The description says:

> When we get more than a thousand ohms, we say "kiloohms".

3300 is more than a thousand, so my interpretation of the description would be that the expected value is `3,3 kiloohms`.

2022-03-14 18:43 UTC, SaschaMann commented
> The return values are described as objects with value and unit keys, not strings, so it's just about using a float for the value.

Some implementations of this exercise use strings as expected value, e.g. C#'s.

2022-03-23 02:37 UTC, SleeplessByte commented
https://neurophysics.ucsd.edu/courses/physics_120/resistorcharts.pdf switches at exactly 1000 ohms. I find that compelling enough to fix the description to `3.3 k`

2026-07-29 05:56 UTC, IsaacG commented
We've gone back and forth on 3300 vs 3.3k. I think the conclusion was that it's simpler to just not add it and leave it unspecified.

2026-07-29 05:56 UTC, closed without merging