Add test cases for array mutation
exercism/problem-specifications pull request #1767
Opened 2021-01-14 17:45 UTC by slaymance

This is a PR in response to [Issue 931](https://github.com/exercism/javascript/issues/931) on the JavaScript track.

This exercise presents a problem in the JavaScript track due to array mutability (I know, classic). Many learners' implementations make use of the `Array.prototype.sort` method to get the top three personal scores. However, in JavaScript, this method mutates the array. This causes subsequent calls to retrieve the array of scores, as well as getting the latest score if the implementation is getting the last score from the scores array, to be different that if these methods were called before the sort occurred.

In JavaScript, our plan is to have some additional test cases that would check the `scores` array and `latestScore` property before and after a call to `personalTopThree` to ensure they are the same. We felt this would be a useful PR to the canonical tests since other languages may also have this issue.

I've placed the additional tests in the `Top 3 scores` block, but would like some input if they make the most sense there. I also created new properties to capture these test cases, though perhaps we may find that unnecessary if we can implement them using existing properties.

2021-01-14 20:43 UTC, SleeplessByte requested changes

2021-01-14 20:43 UTC, SleeplessByte commented on exercises/high-scores/canonical-data.json
> +          "uuid": "",
```suggestion
          "uuid": "2df075f9-fec9-4756-8f40-98c52a11504f",
```

2021-01-14 20:43 UTC, SleeplessByte commented on exercises/high-scores/canonical-data.json
> +          "uuid": "",
```suggestion
          "uuid": "809c4058-7eb1-4206-b01e-79238b9b71bc",
```

2021-01-14 20:44 UTC, SleeplessByte commented
I generated two UUID v4s for ya.

2021-01-15 01:10 UTC, SleeplessByte commented
If this is merged after #1740, this PR should be updated to use the `immutable` scenario.
@exercism/reviewers want to check both out?

2021-01-20 18:38 UTC, SleeplessByte approved these changes

2021-01-20 19:28 UTC, BethanyG approved these changes

2021-01-21 17:52 UTC, glennj commented
The Groovy track also thought about this: https://github.com/exercism/groovy/blob/master/exercises/high-scores/src/test/groovy/HighScoresSpec.groovy#L85

2021-01-23 20:00 UTC, neenjaw approved these changes

2021-01-23 20:13 UTC, SleeplessByte requested changes
Can you update both with the `immutable` scenario?

2021-02-02 17:09 UTC, SleeplessByte commented on exercises/high-scores/canonical-data.json
> +          "property": "latestAfterTopThree",
Too much meaning :). A lot of the exercises can be tested using property-based tests, but sometimes, like right now, we can't. In other exercises we've chosen to _abuse_ the property key adding new "properties", like this one, that name what they intend to do.

In most languages you _could_ implement them as a property on the student's solution, but moreoften you'll write it as a few steps to take inside the test. So in this case: call top three first, then test latest.

2021-02-02 17:10 UTC, SleeplessByte approved these changes

2021-02-02 17:10 UTC, SleeplessByte commented on exercises/high-scores/canonical-data.json
> +          "property": "latestAfterTopThree",
@wolf99 if you're okay with this, can you let us know? I'll hold-off on merging until you say so.

2021-02-02 17:11 UTC, SleeplessByte commented
For the person merging, see https://github.com/exercism/problem-specifications/pull/1767#discussion_r568778682 first.

2021-02-02 17:34 UTC, wolf99 commented on exercises/high-scores/canonical-data.json
> +          "property": "latestAfterTopThree",
Yah, if that's the intended use, then this change LGTM

2021-02-02 21:33 UTC, merged