Revert "Collatz Conjecture: test for non-integers"
exercism/problem-specifications pull request #1897
Opened 2021-12-15 23:27 UTC by SleeplessByte

Reverts exercism/problem-specifications#1820

@wolf99 did you want to do this??

2021-12-15 23:43 UTC, junedev approved these changes

2021-12-17 07:11 UTC, SaschaMann approved these changes

2021-12-20 11:38 UTC, wolf99 commented
No, sorry these tests should stay. It's the `f7176864-e35d-41eb-ba80-0242ac130004` test that should be removed.

Per: https://github.com/exercism/problem-specifications/pull/1820#pullrequestreview-828551671

2021-12-20 11:40 UTC, wolf99 requested changes
Negative and zero tests were OK, its the non-integer (i.e. floating point) test that should be removed.

2021-12-20 11:41 UTC, wolf99 commented
Oh! looking now it seems like it is already removed!
This PR is not needed at all then.

2021-12-20 16:44 UTC, closed without merging