updated the ISBN descreption for additonal clarity
exercism/problem-specifications pull request #1980
Opened 2022-03-04 20:49 UTC by blakeashleyjr

This PR is based on the discussion of this issue.

When using the default code blocks with the text language, the subscript characters are removed. I switched them to block quotes to preserve the subscripts and everything looks good because it is only text anyways. Let me know if this violates a standard somewhere

2022-03-04 20:52 UTC, blakeashleyjr commented
The linter failed because it is confusing the "*"s with emphasis marks when they represent multiplication symbols.

2022-03-05 01:15 UTC, SaschaMann requested changes

2022-03-05 01:15 UTC, SaschaMann commented on exercises/isbn-verifier/description.md
> +> (1₁ * 10 + 2₂ * 9 + 3₃ * 8 + 4₄ * 7 + 5₅ * 6 + 6₆ * 5 + 7₇ * 4 + 8₈ * 3 + 9₉ * 2 + 10₁₀ * 1) mod 11 == 0
This notation is really confusing. I only know digits with indices like this where the index clarifies which base the number is in. I think it was suggested that these should be `d` with subscripts?

2022-03-05 01:16 UTC, SaschaMann commented
> The linter failed because it is confusing the "*"s with emphasis marks when they represent multiplication symbols.

You can escape them with a backslash. But I don't understand why the text block removes subscripts. Did you use the Unicode subscripts or `<sub>`?

2022-03-05 01:43 UTC, blakeashleyjr commented
Thanks @SaschaMann, I corrected the markdown according to your suggestion and switched the digits to a "d" for more clarity. Let me know what you think

The text block removed the Unicode subscripts and <sub> tags for me in VSCode. Interestingly, the tags do work outside of a text block though:

![image](https://user-images.githubusercontent.com/56891775/156862599-c0f3113f-31f1-4b50-ab04-0ad5aff72ba7.png)

I can switch to using <sub> tags but they are likely less supported than the Unicode characters.

2022-03-14 16:19 UTC, angelikatyborska commented
> The text block removed the Unicode subscripts [...] for me in VSCode

Are you sure? They do work for me (a fresh VSC installation on a m1 mac). Here's screenshots of VSC and RubyMine rendering the subscript unicode characters in a text code block:
<img width="1207" alt="Screenshot 2022-03-14 at 17 16 32" src="https://user-images.githubusercontent.com/7852553/158215424-4f0d842a-eee0-4422-a0c2-1e58ba99e12b.png">
<img width="1100" alt="Screenshot 2022-03-14 at 17 16 53" src="https://user-images.githubusercontent.com/7852553/158215446-f65803dc-ed01-4cf4-baeb-edcc6198948c.png">

2022-03-14 17:39 UTC, SaschaMann reviewed
> Are you sure? They do work for me (a fresh VSC installation on a m1 mac). Here's screenshots of VSC and RubyMine rendering the subscript unicode characters in a text code block:

Yeah they work fine for me too.

When we get the equation support that was promised as a launch feature, this would be a great candidate to convert to that.

2022-03-14 17:39 UTC, SaschaMann commented on exercises/isbn-verifier/description.md
> +> (d₁ \* 10 + d₂ \* 9 + d₃ \* 8 + d₄ \* 7 + d₅ \* 6 + d₆ \* 5 + d₇ \* 4 + d₈ \* 3 + d₉ \* 2 + d₁₀ \* 1) mod 11 == 0
```suggestion
```text
(d₁ * 10 + d₂ * 9 + d₃ * 8 + d₄ * 7 + d₅ * 6 + d₆ * 5 + d₇ * 4 + d₈ * 3 + d₉ * 2 + d₁₀ * 1) mod 11 == 0
```
```

2022-03-14 17:39 UTC, SaschaMann commented on exercises/isbn-verifier/description.md
> +> (3 \* 10 + 5 \* 9 + 9 \* 8 + 8 \* 7 + 2 \* 6 + 1 \* 5 + 5 \* 4 + 0 \* 3 + 8 \* 2 + 8 \* 1) mod 11 == 0
```suggestion
```text
(3 * 10 + 5 * 9 + 9 * 8 + 8 * 7 + 2 * 6 + 1 * 5 + 5 * 4 + 0 * 3 + 8 * 2 + 8 * 1) mod 11 == 0
```
```

2022-03-14 21:23 UTC, blakeashleyjr commented
Thank you @SaschaMann and @angelikatyborska for testing that. I do have a couple markdown specific plugins enabled that may be interfering with the text box specifically.

I changed the description according to your suggestions. Let me know what you think now.

2022-03-15 01:29 UTC, SaschaMann approved these changes
Thanks!

@kotp talking about the website/v3 launch.

2022-03-15 07:49 UTC, angelikatyborska approved these changes

2022-03-15 07:51 UTC, ErikSchierboom approved these changes

2022-03-15 07:53 UTC, merged