`state-of-tic-tac-toe`: tweak error nessage and add test case
exercism/problem-specifications pull request #2012
Opened 2022-04-18 01:29 UTC by jiegillet

In the last test, the board is
```
XXX
OOO
   
```
and it's clear that `X` won and `O` kept playing, but for this board:
```
XXX
OOO
XOX
```
it's impossible to determine who won "first". 

And really, it doesn't matter who won, what matters is that this is an impossible board because the players kept going after the game was won, so I'm proposing to tweak the error message to reflect that and add one more test case to justify the change.

Credits to @angelikatyborska for finding this incompleteness issue.

2022-04-18 10:59 UTC, SaschaMann approved these changes
Is reimplementing required for changing the error message?

Either way, this looks good.

2022-04-18 11:29 UTC, jiegillet commented
I guess so, I didn't think so either, but the CI didn't let me change just the error...

2022-04-18 11:47 UTC, SaschaMann commented
The CI script doesn't really consider errors explicitly, it's mostly a side effect. @ErikSchierboom Should error _messages_ be immutable too? To me they seem like descriptions.

2022-04-18 13:37 UTC, SaschaMann commented
I think the question here would be what the error text is. Is it like the description, an error that explains why it should be an error to the maintainers so that they interpret it in a way that makes sense in their language, or is it the actual error message that the student would have to return? To me it seems like it should be the former because it's impossible to write the latter in a language-agnostic way.

If it's the former, it should be mutable.

2022-04-18 15:16 UTC, jiegillet commented
That's true, depending on how you want to implement the exercise, you might not return the error as this exact string, although I do feel that many track probably would do that, since returning an error with string is a pretty standard. I usually choose to do that in Elixir/Elm. Since I can ask students to return strings, why wouldn't I use the one provided to me here?

Another point is that I would want the maintainers to see that an error message has been changed. Does configlet inform people of such a change if the test case has not been reimplemented? If it doesn't, then it's a point for immutable, but I can't remember if it does...

2022-04-19 06:36 UTC, angelikatyborska approved these changes

2022-04-19 07:51 UTC, ErikSchierboom commented
> Another point is that I would want the maintainers to see that an error message has been changed. Does configlet inform people of such a change if the test case has not been reimplemented? If it doesn't, then it's a point for immutable, but I can't remember if it does...

No, we don't show these changes. We've had discussions on the error text before, but we hadn't yet reached a satisfactory conclusion I think. I think I'm still leaning towards reimplementation, as some tracks will be using the error description to influence what code is being generated.

2022-04-19 12:19 UTC, SaschaMann commented
> We've had discussions on the error text before, but we hadn't yet reached a satisfactory conclusion I think. I think I'm still leaning towards reimplementation, as some tracks will be using the error description to influence what code is being generated.

Let's merge it as is then :)

2022-04-19 12:20 UTC, SaschaMann requested changes
~~Actually, I think it might be better to have both test cases but with the same error message. I don't see an obvious reason to remove the old one entirely.~~

(This was nonsense; see below)

2022-04-19 12:27 UTC, jiegillet commented
I'm not sure I understand.
I haven't removed the old test case, I have reimplemented it with the updated error message, and also added a new one with the same error message.

2022-04-19 13:16 UTC, SaschaMann commented on exercises/state-of-tic-tac-toe/canonical-data.json
> +          "description": "Invalid board",
> I just noticed that every test case for invalid board has the exact same description, which will definitely trip up test generators.

See https://github.com/exercism/problem-specifications/pull/1991#discussion_r846418717

2022-04-19 13:48 UTC, jiegillet commented on exercises/state-of-tic-tac-toe/canonical-data.json
> +          "description": "Invalid board",
It's not just the invalid board, most descriptions repeat 3 times...
On the Elixir implementation I added (1) (2) (3)... To all descriptions. It was a bit tedious.
Shall I do the same, or better descriptions?

2022-04-19 13:50 UTC, SaschaMann commented on exercises/state-of-tic-tac-toe/canonical-data.json
> +          "description": "Invalid board",
> Shall I do the same, or better descriptions?

Adding the errors to the descriptions here seems reasonable but I'd leave the other descriptions for a different PR.

2022-04-20 10:34 UTC, ErikSchierboom approved these changes
Approved. As suggested, the descriptions can be improved in a follow-up PR.

2022-04-20 12:35 UTC, merged