Remove broken link in grade school. fixes #2040
exercism/problem-specifications pull request #2041
Opened 2022-05-19 17:14 UTC by ceddlyburge

2022-05-19 17:38 UTC, SaschaMann requested changes

2022-05-19 17:38 UTC, SaschaMann commented on exercises/grade-school/metadata.toml
> -source = "A pairing session with Phil Battos at gSchool"
In line with https://github.com/exercism/problem-specifications/pull/1663 I'd suggest keeping the source and only removing the URL. The source itself hasn't changed.

2022-05-19 19:46 UTC, SaschaMann approved these changes

2022-05-20 07:33 UTC, ErikSchierboom approved these changes

2022-05-21 05:33 UTC, jiegillet approved these changes

2022-05-21 05:34 UTC, merged

2022-05-21 12:25 UTC, ceddlyburge commented
Hi @SaschaMann @ErikSchierboom this change fails the configlet CI check when I sync it in to the Elm repository.
https://github.com/exercism/elm/runs/6536869034?check_suite_focus=true

Can we fix this by just removing `source`, or will we need to update configlet?

Thanks, Cedd