scrabble-score: convert to instructions and introduction
exercism/problem-specifications pull request #2417
Opened 2024-04-03 12:42 UTC by ErikSchierboom

2024-04-03 17:13 UTC, IsaacG requested changes

2024-04-03 19:30 UTC, MatthijsBlom approved these changes

2024-04-03 19:30 UTC, MatthijsBlom commented on exercises/scrabble-score/introduction.md
> +[Scrabble][wikipedia] is a word game where players place letter tiles on a board to form words. Each letter has a value. A word's score is the sum of its letter values.
Nitpick:

```suggestion
[Scrabble][wikipedia] is a word game where players place letter tiles on a board to form words. Each letter has a value. A word's score is the sum of its letters' values.
```

2024-04-03 19:30 UTC, MatthijsBlom commented on exercises/scrabble-score/instructions.md
> +```
This _could_ be a table instead of a code block.

2024-04-04 11:32 UTC, IsaacG approved these changes

2024-04-04 13:09 UTC, iHiD commented on exercises/scrabble-score/instructions.md
> +
```suggestion
```

2024-04-04 13:09 UTC, iHiD commented on exercises/scrabble-score/instructions.md
> +The word "cabbage" is worth 14 points:
```suggestion
For example, the word "cabbage" is worth 14 points:
```

2024-04-04 13:11 UTC, iHiD commented on exercises/scrabble-score/instructions.md
> +Compute a word's Scrabble score by summing its letters' values.
```suggestion
Your task is to compute a word's Scrabble score by summing the values of its letters.
```

I suggest this slight variation so we don't have the same phrase "summing it's letter's values" twice in a row.

2024-04-04 13:24 UTC, merged

2024-04-04 13:24 UTC, ErikSchierboom commented
Thanks everybody! I merged this as we need it for our video :)